### ISSUE TITLE
Cannot find module 'puppeteer-core/lib/cjs/common/Browser'

### ISSUE THREAD

**Issue by erdinc** [luisfarzati/chromda#10]
I just followed the instructions on README, deployed to AWS and used the json to test the service but I got this error.
```
{
  "errorType": "Error",
  "errorMessage": "Cannot find module 'puppeteer-core/lib/cjs/common/Browser'\nRequire stack:\n- /opt/nodejs/node_modules/chrome-aws-lambda/source/puppeteer/lib/Browser.js\n- /opt/nodejs/node_modules/chrome-aws-lambda/source/index.js\n- /var/task/src/captureScreenshot.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
  "trace": [
    "Error: Cannot find module 'puppeteer-core/lib/cjs/common/Browser'",
    "Require stack:",
    "- /opt/nodejs/node_modules/chrome-aws-lambda/source/puppeteer/lib/Browser.js",
    "- /opt/nodejs/node_modules/chrome-aws-lambda/source/index.js",
    "- /var/task/src/captureScreenshot.js",
    "- /var/runtime/UserFunction.js",
    "- /var/runtime/index.js",
    "    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:842:27)",
    "    at Module.require (internal/modules/cjs/loader.js:1026:19)",
    "    at require (internal/modules/cjs/helpers.js:72:18)",
    "    at Object.<anonymous> (/opt/nodejs/node_modules/chrome-aws-lambda/source/puppeteer/lib/Browser.js:6:11)",
    "    at Module._compile (internal/modules/cjs/loader.js:1138:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)",
    "    at Module.load (internal/modules/cjs/loader.js:986:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:879:14)",
    "    at Module.require (internal/modules/cjs/loader.js:1026:19)"
  ]
 #}
```

**Comment by erdinc** [comment]
I figured out, you need to update serverless.yml file 
`    - arn:aws:lambda:${self:provider.region}:764866452798:layer:chrome-aws-lambda:19`
to latest version
`    - arn:aws:lambda:${self:provider.region}:764866452798:layer:chrome-aws-lambda:21`
